version: "3.9"  # optional since v1.27.0
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    network_mode: host # for dev only
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres